spring:
  application:
    name: startup

  datasource:
    url: jdbc:postgresql://localhost:5432/Payroll
    username: postgres
    password: tShembho2003
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
